# KaggleSlayer Configuration

# Pipeline Settings
pipeline:
  cv_folds: 5
  cv_random_state: 42
  optuna_trials: 20
  optuna_timeout: 300
  max_features_to_create: 25
  polynomial_degree: 2

# Data Processing
data:
  drop_missing_threshold: 0.9
  correlation_threshold: 0.95
  variance_threshold: 0.01

# Model Selection
model_selection:
  classification_metric: 'accuracy'  # Options: 'accuracy', 'roc_auc', 'f1', 'precision', 'recall'
  regression_metric: 'neg_mean_squared_error'  # Options: 'neg_mean_squared_error', 'neg_mean_absolute_error', 'r2'
